import './globals.css'
import type { Metadata } from 'next'
import { montserrat } from './fonts'
import ContactHeader from './components/ContactHeader'
import Navbar from './components/Navbar'

export const metadata: Metadata = {
  title: 'Eric\'s 360insights Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>

        <ContactHeader />
          <Navbar />
          <main>
            {children}
          </main>
      </body>
    </html>
  )
}
